default.extend-ignore-re = ["\\\\u\\{[0-9A-Za-z]*\\}"]
[files]
extend-exclude = ["src/matcher_inner/tests.rs","src/matcher_inner/pattern/tests.rs", "src/matcher_inner/utf32_str/tests.rs", "src/pattern/tests.rs", "*.html"]
